builds:
  - id: kubectl-whoami
    main: ./
    binary: kubectl-whoami
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/bdwyertech/kubectl-whoami/pkg/cmd.Version={{.Version}}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
      - -trimpath

archives:
  - builds:
      - kubectl-whoami
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE
